' The C4 PlantUML example here is thanks to the C4 PlantUML team.
' The UML is copied from the "Big Bank with Icons" example.
'
' C4 PlantUML repository:
' https://github.com/plantuml-stdlib/C4-PlantUML/
'
' C4 PlantUML samples:
' https://github.com/plantuml-stdlib/C4-PlantUML/tree/master/samples
'
' You can include the C4 PlantUML file in various ways.
'
' To include the default way, uncomment this line:
' !include <C4/C4_Container>
'
' To include the remote file, uncomment this line:
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
'
' To include a local file, uncomment this line:
' !include C4_Context.puml

@startuml

' Many creators of C4 diagrams like to add icons.
' This example shows how to use the built-in icons.
'
' To see all available icons, one way is this link:
' https://html-preview.github.io/?url=https://github.com/tupadr3/plantuml-icon-font-sprites/blob/v3.0.0/icons/index.html
'
' This example loads the current built-in icons via remote GitHub link.
' There are other ways to do this, such as via your own local file,
' of via typical PlantUML syntax which loads the most-recent release.
'
' This example aims to show you the most-up-to-date way.
'
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons2/angular.puml
!include $ICONURL/devicons2/dot_net.puml
!include $ICONURL/devicons2/java.puml
!include $ICONURL/font-awesome-6/server.puml
!include $ICONURL/font-awesome-6/envelope.puml
!include $ICONURL/font-awesome-6/database.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title C4 Model container diagram example

Person(customer, Customer, "A customer of the bank, with personal bank accounts")

System_Boundary(c1, "Internet Banking") {
    Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA", "java")
    Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to customers via their web browser", "angular")
    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device", "dotnet")
    ContainerDb(database, "Database", "SQL Database", "Stores user registration information, hashed auth credentials, access logs, etc.", "database")
    Container(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API", "server")
}

System_Ext(email_system, "E-Mail System", "The internal Microsoft Exchange system", "envelope")
System_Ext(banking_system, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(customer, web_app, "Uses", "HTTPS")
Rel(customer, spa, "Uses", "HTTPS")
Rel(customer, mobile_app, "Uses")

Rel_Neighbor(web_app, spa, "Delivers")
Rel(spa, backend_api, "Uses", "async, JSON/HTTPS")
Rel(mobile_app, backend_api, "Uses", "async, JSON/HTTPS")
Rel_Back_Neighbor(database, backend_api, "Reads from and writes to", "sync, JDBC")

Rel_Back(customer, email_system, "Sends e-mails to")
Rel_Back(email_system, backend_api, "Sends e-mails using", "sync, SMTP")
Rel_Neighbor(backend_api, banking_system, "Uses", "sync/async, XML/HTTPS")
@enduml